# Stage 1
FROM node:10-alpine as build-step

RUN mkdir -p /app

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . .

RUN npm run build --prod

#CMD ng serve --host 0.0.0.0
# Stage 2
FROM nginx:1.17.1-alpine

COPY --from=build-step /app/docs /usr/share/nginx/html
